# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# User.create(email: ENV['MAIL_ADDRESS'], password: ENV['PASSWORD'], name: '名無しの浦木', room: '627', language: 'Japanese', admin: true)
HeadLetter.create([
    {letter: "あ", language: "Japanese"},
    {letter: "い", language: "Japanese"},
    {letter: "う", language: "Japanese"},
    {letter: "え", language: "Japanese"},
    {letter: "お", language: "Japanese"},
    {letter: "か・が", language: "Japanese"},
    {letter: "き・ぎ", language: "Japanese"},
    {letter: "く・ぐ", language: "Japanese"},
    {letter: "け・げ", language: "Japanese"},
    {letter: "こ・ご", language: "Japanese"},
    {letter: "さ・ざ", language: "Japanese"},
    {letter: "し・じ", language: "Japanese"},
    {letter: "す・ず", language: "Japanese"},
    {letter: "せ・ぜ", language: "Japanese"},
    {letter: "そ・ぞ", language: "Japanese"},
    {letter: "た・だ", language: "Japanese"},
    {letter: "ち・ぢ", language: "Japanese"},
    {letter: "つ・づ", language: "Japanese"},
    {letter: "て・で", language: "Japanese"},
    {letter: "と・ど", language: "Japanese"},
    {letter: "な", language: "Japanese"},
    {letter: "に", language: "Japanese"},
    {letter: "ぬ", language: "Japanese"},
    {letter: "ね", language: "Japanese"},
    {letter: "の", language: "Japanese"},
    {letter: "は・ば・ぱ", language: "Japanese"},
    {letter: "ひ・び・ぴ", language: "Japanese"},
    {letter: "ふ・ぶ・ぷ", language: "Japanese"},
    {letter: "へ・べ・ぺ", language: "Japanese"},
    {letter: "ほ・ぼ・ぽ", language: "Japanese"},
    {letter: "ま", language: "Japanese"},
    {letter: "み", language: "Japanese"},
    {letter: "む", language: "Japanese"},
    {letter: "め", language: "Japanese"},
    {letter: "も", language: "Japanese"},
    {letter: "や", language: "Japanese"},
    {letter: "ゆ", language: "Japanese"},
    {letter: "よ", language: "Japanese"},
    {letter: "ら", language: "Japanese"},
    {letter: "り", language: "Japanese"},
    {letter: "る", language: "Japanese"},
    {letter: "れ", language: "Japanese"},
    {letter: "ろ", language: "Japanese"},
    {letter: "わ", language: "Japanese"},
    {letter: "A", language: "English"},
    {letter: "B", language: "English"},
    {letter: "C", language: "English"},
    {letter: "D", language: "English"},
    {letter: "E", language: "English"},
    {letter: "F", language: "English"},
    {letter: "G", language: "English"},
    {letter: "H", language: "English"},
    {letter: "I", language: "English"},
    {letter: "J", language: "English"},
    {letter: "K", language: "English"},
    {letter: "L", language: "English"},
    {letter: "M", language: "English"},
    {letter: "N", language: "English"},
    {letter: "O", language: "English"},
    {letter: "P", language: "English"},
    {letter: "Q", language: "English"},
    {letter: "R", language: "English"},
    {letter: "S", language: "English"},
    {letter: "T", language: "English"},
    {letter: "U", language: "English"},
    {letter: "V", language: "English"},
    {letter: "W", language: "English"},
    {letter: "X", language: "English"},
    {letter: "Y", language: "English"},
    {letter: "Z", language: "English"}
])